apiVersion: apps/v1
kind: Deployment
metadata:
  name: bp-database
  namespace: bp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bp-database
  template:
    metadata:
      labels:
        app: bp-database
    spec:
      containers:
      - name: bp-database
        image: localhost:5000/bp-database:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: DATABASE_URL
          value: postgresql://postgres:postgres@localhost:5432/bp
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: bp-db-pvc
