apiVersion: v1
kind: Service
metadata:
  name: bp-database-service
  namespace: bp-app
spec:
  selector:
    app: bp-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP