apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: bp-app
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
  